
asteroid: asteroidGame.c graphics.c asteroid.c scoreboard.c player.c
	clang -std=c11 -pedantic -g asteroidGame.c graphics.c effects.c asteroid.c scoreboard.c player.c  -lSDL2 -lSDL2_ttf -o asteroid \
	 -fsanitize=undefined -fsanitize=address



